### ISSUE TITLE
add support in CsfGraph for instatiating using a networkx graph

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/N2V#101]
Per convo with @deepakunni3 and @realmarcin, it'd be nice if we could instantiate a `CsfGraph` by handing it a networkx graph, so we could then leverage KGX to easily import graphs in any format KGX supports (currently includes rdf, owl, pandas, json, tsv, csv, networkx, neo4j)

Glad to do this if it sounds reasonable

**Comment by callahantiff** [comment]
@justaddcoffee - sounds like an awesome idea!

**Comment by justaddcoffee** [comment]
Possibly can close this ticket - we can't hand CSFGraph a networkx graph like this ticket says, but we can instantiated graph using TSV formatted files from KGX.

@callahantiff @deepakunni3 should we close this?

**Comment by deepakunni3** [comment]
Perfect! Yes, let's close this then 👍
