### ISSUE TITLE
Add better support for node types

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/N2V#104]
@pnrobinson I think we're near the point where we can tests some KGs emitted by kg_covid_19. 

These obviously will be heterogeneous graphs though, so we probably should make a decision about node types - i.e. how to refactor nodes types to not rely on the first character of the node name (`node[0]`). (See also #26) 

A proposal:
- make a `node` class with an `attr` called `node_type`. 
- change `CsfGraph` to optionally accept another file `nodes.tsv` with two columns:
`node`\t`node_type`
and use the second column to populate `node_type` in the `node` class. Nodes not mentioned in this file are set to `node_type` `None`, and all `node`s are `None` if the file is not present.
- refactor all methods that deal with node types (e.g. `__preprocess_transition_probs_xn2v()`) to look for this info in the `node` class

Peter, others, thoughts?

**Comment by pnrobinson** [comment]
What about the case where we have different edge types though? 
Somehow it feels less error prone to have everything in one input file.
What about

node1name[,node1type]  node2name[,node2type] edge1name[,edge1type]

where [ ] means optional

Possibly we could make the user pass a flag such as --typed_graph to use a different constructor for this.

No strong feelings about this, just putting this up for discussion

**Comment by justaddcoffee** [comment]
Yes, let's discuss! 

> node1name[,node1type] node2name[,node2type] edge1name[,edge1type]

This would work too, but a few drawbacks:
- node types have to be repeated for each edge in which a node appears
- node type for a given node will conflict if the node type isn't exactly the same every time it appears in the edge file - which do you pick? 
To mean it feels more error prone than if the node type is listed once in a separate file - my $0.02

**Comment by pnrobinson** [comment]
sufficiently equitable...
Maybe having a separate file of types that could specify both node and edge types?

**Comment by justaddcoffee** [comment]
> Maybe having a separate file of types that could specify both node and edge types?

Is a separate edge type file necessary? It seems like this info belongs in the current `.edges` file.

I was thinking we could align with and crib @deepakunni3 's `KGX` tsv formats (see `nodes.tsv` and `edges.tsv` [here](https://github.com/NCATS-Tangerine/kgx/blob/master/data-preparation.md), since he's already thought this through, and we're also going to consume graphs from KGX soon.

The existing `.edges` files in N2V pretty much correspond to to KGX's `edges.tsv`, I think - the `nodes.tsv` I propose above would correspond to KGX `nodes.tsv`....

**Comment by pnrobinson** [comment]
didnt realize all of this existed. Why not just adopt the KGX formats?

**Comment by justaddcoffee** [comment]
> didnt realize all of this existed. Why not just adopt the KGX formats?

Sure, let's do that! 

Some more considerations: 
- We need to I guess invent an edge label for negative edges - these don't exist in Deepak's KGX realm

- This new format will require Vida and others who are using N2V now to do a tiny bit of data wrangling (basically just add an edge label in the second column of the `.edges` file, and optionally produce a `nodes.tsv` file)

**Comment by deepakunni3** [comment]
@justaddcoffee What do you mean by edge label for negative edges? Could you provide an example?

**Comment by justaddcoffee** [comment]
> What do you mean by edge label for negative edges?

@deepakunni3 well, N2V doesn't have any edge labels for negative edges. I just mean that if we switch to KGX .tsv format, and we also ingest negative edges (like [this](https://github.com/monarch-initiative/N2V/blob/master/neg_test_edges) and [this](https://github.com/monarch-initiative/N2V/blob/master/neg_train_edges)), then the format requires us to make up an edge label for negative edges. 

An obvious solution is to ingest negative edges as a different kind of .tsv, with two fields (node1 and node2), just thinking ahead I guess.

**Comment by deepakunni3** [comment]
So you just need to differentiate between normal edges and negative edges?

Perhaps something like this:
```
subject  edge_label  object  negative_edge
node1  related_to  node2  false
node1  related_to  node10  true
node1  related_to  node20  true
```

You can look for `negative_edge` property on the edge and treat these edges as such when parsing from networkx graph to CsfGraph?

Would that help?

**Comment by justaddcoffee** [comment]
> Would that help?

Sure, that would work and seems sensible

**Comment by pnrobinson** [comment]
Now the graph class is returning lists of ints as well as a dictionary and reverse dictionary.
I am wondering in terms of architexture if we should do something like this in the constructor of the graph class
```
nodetype_to_key_map = defaultdict(int)
key_to_nodetype_map = defaultdict(str)
edgetype_to_key_map = defaultdict(int)
key_to_edgetype_map = defaultdict(str)
## The above are small maps that relate the enums to integers 
## The following relate the actual nodes and eges to integers
nodes = []
nodenames = []
nodetypes = []
edges = []
edgesnames = []
```
(while we are parsing the XKG files, we keep track of the strings that represent the edge and node types and create an integer code for each of them)
Then, when are are parsing the file
```
current_node_idx = 0
 for line in f:
    fields = line.rstrip('\n').split()
    node_a = fields[0]
    node_b = fields[1]
    (..we would also be ingesting the node types here..)
    node_a_type = parse(?) # this is a string, we will add it to nodetype_to_key_map/key_to_nodetype_map
    node_b_type = parse(?)
    nodes.add(current_node_idx)
    nodenames.add(node_a)
    nodetypes.add(nodetype_to_key_map.get(node_a_type))
    nodes.add(node_a)
    (etc)
```
Then, when we are doing the walk, we can basically use the indices of the nodes and edges, and if we need to know their types we can simply look them up.
The alternative would be to create classes for Nodes and Edges -- this would require more refactoring.

Thoughts?

**Comment by justaddcoffee** [comment]
> Then, when we are doing the walk, we can basically use the indices of the nodes and edges, and if we need to know their types we can simply look them up.

Okay, using a dictionary to manage node type seems reasonable and probably way easier to implement (and maybe more performant) than using a Node class, considering how things work now (using indices and dictionaries/reverse dictionaries to manage nodes).

I'll work on this today

**Comment by justaddcoffee** [comment]
@pnrobinson still working on a PR #120 to address this - I'm following the spirit of what you describe above, although I've deviated slightly. I'm unit testing everything, so should be easy to refactor. Glad to describe the refactor tomorrow on the N2V call if you can make it
