### ISSUE TITLE
Create link prediction scoring funcs utility file

### ISSUE THREAD

**Issue by callahantiff** [monarch-initiative/N2V#106]
Creating this issue as part of the conversation in #105.

**TODO - Add Link Prediction Scoring functions to Utility Script** 
- [x] Common Neighbors      
- [x] Jaccard’s Coefficient      
- [x] Adamic-Adar      
- [x] Preferential Attachment       
- [ ] See [here](https://github.com/callahantiff/owl-nets/blob/master/LinkPrediction.py) for additional scoring functions worth considering, including:  
  - Degree Product
  - Sorenson Similarity 
  - Leicht-Holme-Newman Similarity  
  - Shortest Path  
  - Resource Allocation  
  - Katz  
  - SimRank  
  - Rooted Page Rank

<br>

@vidarmehr - Does that cover everything?

**Comment by vidarmehr** [comment]
@callahantiff Yes. Thank you, Tiffany!

**Comment by vidarmehr** [comment]
@vidarmehr I will work on this over the weekend.

**Comment by vidarmehr** [comment]
@callahantiff  I have created the branch linkprediction_functions in which I have implemented Degree Product score, Jaccard's score, Adamic adar's index and Common Neighbors's score in link_prediction_functions.py. I am going to add more unittests in test_link_prediction_functions.py  make a pull request and ask you to review the code. Thanks.

**Comment by callahantiff** [comment]
> @callahantiff I have created the branch "linkprediction_functions" in which I have implemented Degree Product score, Jaccard's score, Adamic adar's index and Common Neighbors's score in link_prediction_functions.py. I am going to add more unittests in test_link_prediction_functions.py, make a pull request and ask you to review the code. Thanks.

Awesome @vidarmehr, that sounds fantastic!

**Comment by vidarmehr** [comment]
Degree Product score, Jaccard's score, Adamic adar's index and Common Neighbors's score were implemented in the  link_prediction_functions.py. branch which was merged to develop. So, I close this issue.
