### ISSUE TITLE
How to format input data for GloVe

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#107]
Hi everybody,
I am adapting a keras version of GloVe to use the tf keras (only small changes needed).
I am wondering if we want to have a standard way of passing the data to the models, and if we
are planning on changing anything in the present constructors for word2vec.
This is an excerpt of what the function looks like

```
v_size = 3000
tokenizer = Tokenizer(num_words=v_size, oov_token='UNK')
tokenizer.fit_on_texts(docs)

def generate_cooc_matrix(text, tokenizer, window_size, n_vocab, use_weighting=True):
    sequences = tokenizer.texts_to_sequences(text)

    cooc_mat = lil_matrix((n_vocab, n_vocab), dtype=np.float32)
    for sequence in sequences:
        for i, wi in zip(np.arange(window_size, len(sequence) - window_size), sequence[window_size:-window_size]):
            context_window = sequence[i - window_size: i + window_size + 1]
            distances = np.abs(np.arange(-window_size, window_size + 1))
            distances[window_size] = 1.0
            nom = np.ones(shape=(window_size * 2 + 1,), dtype=np.float32)
            nom[window_size] = 0.0

            if use_weighting:
                cooc_mat[wi, context_window] += nom / distances  # Update element
            else:
                cooc_mat[wi, context_window] += nom
    return cooc_mat
```

I am a little worried this might not be efficient enough for the datasets that we want to use, but hopefully we can speed things up iteratively

**Comment by deepakunni3** [comment]
@callahantiff and I have been exploring ways to standardize on how data is passed to models, the data structure used, configuration of parameters, and more. This goes back to the use of TensorFlow and its API for achieving improvements to the N2V codebase. 

Perhaps we can talk more on this sometime this week?

**Comment by callahantiff** [comment]
> @callahantiff and I have been exploring ways to standardize on how data is passed to models, the data structure used, configuration of parameters, and more. This goes back to the use of TensorFlow and its API for achieving improvements to the N2V codebase.
> 
> Perhaps we can talk more on this sometime this week?

@deepakunni3 - Happy to do that. Want to set something up over email?

**Comment by pnrobinson** [comment]
The GloVe class now uses the text_encoder to input data. If a list of lists is passed, it should directly use them -- I think we can close this and we may need a new issue to put RW data into GloVe
