### ISSUE TITLE
model_to_dot

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#109]
We should explore the model_to_dot facilities of keras for generating decent-looking graphics for publication, e.g., 
```
from keras.utils.vis_utils import model_to_dot
SVG(model_to_dot(model, show_shapes=True, show_layer_names=False, 
                 rankdir='TB').create(prog='dot', format='svg'))
```

**Comment by justaddcoffee** [comment]
Thanks @pnrobinson, I didn't know this existed in keras - should come in handy when we start writing this up to publish

**Comment by pnrobinson** [comment]
It looks like we will not be able to use the keras API for this project and so we will have to make our own graphics...
