### ISSUE TITLE
Various CI service integration

### ISSUE THREAD

**Issue by LucaCappelletti94** [monarch-initiative/N2V#11]
Currently, it is not possible to integrate the repository with various CI services to automate testing and code evaluation. How is the process of approval by the admins going?

I believe that any person that is part of [TheJacksonLaboratory](https://github.com/TheJacksonLaboratory) organization on GitHub should be able to add the integrations, maybe [Peter](https://github.com/pnrobinson) could be added to it?

**Comment by pnrobinson** [comment]
I have asked them to provide permissions and am waiting for a response.

**Comment by justaddcoffee** [comment]
I think we can close this issue?
