### ISSUE TITLE
hetnode2vec_tf

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/N2V#128]
@pnrobinson Hi Peter, I noticed that hetnode2vec_tf has still the old version of get_alias_edge_xn2v. I create a new branch and will update hetnode2vec_tf.py and the tests according to the latest change that I had made.

**Comment by pnrobinson** [comment]
Sounds great -- please update the branch. If things are ok, let's delete one of the two hetnode2vec files to avoid confusion. Also, please merge the link prediction branch and then we should polish and begin testing on real data!

**Comment by vidarmehr** [comment]
Sure, Peter! I will check if hetnode2vec_tf works well or not. If yes, then I will keep the hetnode2vec_tf.py.

I will wait for Tiffany to approve the pull request (link prediction functions to develop). She said that she will review the code today.

**Comment by vidarmehr** [comment]
hetnode2vec_tf and test_hetnode2vec_tf have been updated in the new branch het_n2v_tf. I get error messages in both branches develop and het_n2v_tf when I run link prediction. I will submit issues and fix them before merging het_n2v_tf to develop.

**Comment by vidarmehr** [comment]
The issues are related to word2vec. I try to solve them.

**Comment by vidarmehr** [comment]
I merged the het_n2v_tf to develop and deleted the het_n2v_tf branch. Travis was failing due to some typing errors. 

The random walk in heterogeneous node2vec is now up to date and all tests pass. However, to check if the heterogeneous node2vec works or not, we should test it on some heterogeneous graphs.
