### ISSUE TITLE
error: runLinkPrediction_with_validation_ppi.py

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/N2V#130]
> Traceback (most recent call last):
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_with_validation_ppi.py", line 192, in <module>
    main(args)
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_with_validation_ppi.py", line 186, in main
    learn_embeddings(walks, pos_train_graph, args.w2v_model)
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_with_validation_ppi.py", line 126, in learn_embeddings
    model.train(display_step=100)
TypeError: train() got an unexpected keyword argument 'display_step'

@callahantiff Would you please take a look at this issue?Thanks.

**Comment by pnrobinson** [comment]
I think I may have removed this variable since we need to rethink the display functionality. For now, we could just re-add this variable, or remove it from the function call but we need to rethink this!

**Comment by vidarmehr** [comment]
@pnrobinson Thanks, Peter. So, for now, I will remove it from the function call.

**Comment by vidarmehr** [comment]
Now, runLinkPrediction_with_validation_ppi.py runs with no error.

**Comment by callahantiff** [comment]
@vidarmehr and @pnrobinson - you guys make a good team! 😄 I am glad to hear that everything is working again.

**Comment by vidarmehr** [comment]
> @vidarmehr and @pnrobinson - you guys make a good team! 😄 I am glad to hear that everything is working again.

Thank you, Tiffany! WE are all make a good team:)
