### ISSUE TITLE
results don't match!

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/N2V#135]
I ran link prediction (run_LinkPrediction_with_validation) on the train/valid/test set of ppi data that I had generated before and did not get the same result as before! I get AUC around 0.5 after 150,000 num_steps with Skipgram and CBOW. I do not think that i have made a stupid mistake but I am going to read the word2vec and find what caused this difference.

**Comment by pnrobinson** [comment]
@vidarmehr  Should we do a code review at 2:30PM -- hopefully there is just some simple mistake that we can fix

**Comment by vidarmehr** [comment]
> @vidarmehr Should we do a code review at 2:30PM -- hopefully there is just some simple mistake that we can fix

Yes, Peter. Thank you very much for your help.

**Comment by pnrobinson** [comment]
Hopefully it was the fact that RaggedTensor was not getting recognized as a list of lists
https://github.com/monarch-initiative/N2V/compare/develop...detectRagged?expand=1

**Comment by vidarmehr** [comment]
Still the AUC is around 0.5. I used num_steps=5000,  50,000 and 150,000.

**Comment by justaddcoffee** [comment]
@vidarmehr could you possibly post the exact command you ran, and also links to the edge files we should use to try and reproduce this error? (Sorry, you've probably already posted this somewhere...)

**Comment by vidarmehr** [comment]
@justaddcoffee 
Hi Justin, Thanks a lot for your help.
I just share the google drive folder containing the edge files that you need to run link prediction.
https://drive.google.com/drive/u/0/folders/1g61minrM8DYqnqQifbErsbbrMUPekRMm

Here is the command to run the code:
`python  runLinkPrediction_with_validation_ppi.py`
It runs the link prediction code with validation on train/validation/test sets with some default parameters like:
p=1, q=1, skipgram model for word2vec, logistic regression as the classifier, num_steps=150000

Please remember to set the paths to the input edge files by adding:
`--pos_train path-to-the-pos-train-edges   --pos_valid  path-to-the-pos-validation-edges  --pos_test pth_to_the_pos_test_edges`  
similarly for negative edges:
`--neg_train path-to-the-neg-train-edges   --neg_valid  path-to-the-neg-validation-edges  --neg_test path_to_the_neg_test_edges`  

examples:
`python runLinkPrediction_with_validation_ppi.py  --p 2 --q 3 --num_steps 10000  --classifier RF` 

`python runLinkPrediction_with_validation_ppi.py  --p 2  --num_steps 10000  --embedding_size 100 --w2v_model CBOW` 

Please let me know if you have any questions. Thanks.

**Comment by justaddcoffee** [comment]
hi @vidarmehr @realmarcin - I just merged the fixes the group suggested (#141)

Could you guys let us know if this fixes/improved the ROC score for you?

**Comment by vidarmehr** [comment]
@justaddcoffee Thank you very much, Justin! I will run the code on the cluster.

**Comment by vidarmehr** [comment]
Hi everyone,
Good news! I ran link prediction (with validation) on the ppi data set with default parameters p=1,q=1, Skipgram model for word2vec, Logistic regression classifier and the results are:

n_epochs=1:
AUC score (training): 0.7826864458285363 
AUC score (validation): 0.7804941668369281 
AUC score (test): 0.7797414042943122 

n_epochs=2:
AUC score (training): 0.8196919169001615 
AUC score (validation): 0.8203164357063712 
AUC score (test): 0.8178015448505055 

I am going to test it with different parameters and also with CBOW and  random forest classifier.

**Comment by justaddcoffee** [comment]
Excellent Vida! 

The hackathon quashed that bug pretty quickly - Linus's Law in action!

**Comment by vidarmehr** [comment]
@pnrobinson @justaddcoffee @callahantiff @LucaCappelletti94 @realmarcin @deepakunni3 Thank you everyone for your help!
