### ISSUE TITLE
Pickle or otherwise save random walks so they can be reused

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/N2V#139]
Per convo in N2V meeting

This would be useful to reuse walks and speed up runtime for different learning tasks or different classifiers, etc

@realmarcin

**Comment by deepakunni3** [comment]
@justaddcoffee Is this desired? If so, I can look into this

**Comment by pnrobinson** [comment]
@deepakunni3  -- definitely we should be able to pickle/unpickle the walks data and the embeddings, it would be great to have you think about this!

**Comment by justaddcoffee** [comment]
Yeah, the walk can be pretty computationally painful - it'd be good to have the option to save off walks and reuse them!

**Comment by deepakunni3** [comment]
Okay, I'll start working on this 👍
