### ISSUE TITLE
Manuscript title

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#143]
Hi everybody,
can we start to plan the manuscript? I am guessing we will need this week for testing and polishing and next week we can go for the final results?

What about

```
Optimized embedding improves accuracy of link prediction by node2vec
```

**Comment by callahantiff** [comment]
Sounds great Peter!

One extension idea to your title (since we now offer more than node2vec :D):

`Optimized node embedding improves link prediction accuracy`

OR

`Optimized heterogeneous graph embedding improves link prediction accuracy`

**Comment by pnrobinson** [comment]
@callahantiff 
I was thinking the first paper could be about node2vec + SG/CBOW/GloVe with the Bayesian parameter optimization. It might be easiest to write the paper about just this topic, but of course we should continue with the heterogeneous graphs!

**Comment by callahantiff** [comment]
@pnrobinson - sounds good to me!

**Comment by justaddcoffee** [comment]
Sounds good to me too. Hope to do some test runs on the new heterogeneous code this week - probably will take a little iterating to optimize things for het graphs like kg-covid-19

**Comment by deepakunni3** [comment]
@pnrobinson Sounds good!
Makes sense to have a focused paper first, and then extend that further. 👍

**Comment by pnrobinson** [comment]
OK, I have updated the title. Can we work on a complete authors' list? Right now I have

Vida Ravanmehr, Tiffany Callahan, Luca Capelletti, Deepak Unni, Justin Reese, Michael Gargano, Hannah Blau, Giorgio Valentini, Peter Robinson,

but I am not sure if the order of authors is correct and we should invite others to join as well, esp. Chris. Who am I forgetting? Who else would like to work on writing the manuscript?

**Comment by vidarmehr** [comment]
> OK, I have updated the title. Can we work on a complete authors' list? Right now I have
> 
> Vida Ravanmehr, Tiffany Callahan, Luca Capelletti, Deepak Unni, Justin Reese, Michael Gargano, Hannah Blau, Giorgio Valentini, Peter Robinson,
> 
> but I am not sure if the order of authors is correct and we should invite others to join as well, esp. Chris. Who am I forgetting? Who else would like to work on writing the manuscript?

Marcin is missing.

**Comment by pnrobinson** [comment]
ups sorry. Marcin, you get one beer from me!

**Comment by pnrobinson** [comment]
sending around draft by mail now!
