### ISSUE TITLE
pull requests: merge to develop or master

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/N2V#147]
@pnrobinson Hi Peter, It seems some of the new pull requests were made to merge branches to master branch. I think it would be better to make sure that all branches are merged to develop branch first, right?

**Comment by pnrobinson** [comment]
Yes  please -- all PRs should be to develop!
We should merge develop into master now.
When we are doing the testing, we should write down the version of master we are using.
Please let's do this
https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by justaddcoffee** [comment]
@pnrobinson okay, sounds good. Sorry to break protocol, I just made that last PR to master b/c Chris pinged me about master branch failing, and I thought I'd fix that since it was a fairly small error...

**Comment by vidarmehr** [comment]
@justaddcoffee Thank you, Justin. No problem. Please use develop branch if you or Chris want to run the link prediction code.
