### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#148]
We need a license for this project.
What do people think about GPL?

https://en.wikipedia.org/wiki/GNU_General_Public_License

or we could go with Apache 2 like TensorFlow does
https://github.com/tensorflow/tensorflow/blob/master/LICENSE

**Comment by callahantiff** [comment]
I also tend to use Apache 2. I love this website: [https://choosealicense.com/](https://choosealicense.com/), in case you want a different way to think about it.

**Comment by deepakunni3** [comment]
I would also recommend BSD3: https://choosealicense.com/licenses/bsd-3-clause/

**Comment by justaddcoffee** [comment]
Any license that allows free reuse at least for academic purposes is fine by me. 

If we have questions on the finer points, Seth (@kltm)is a fount of license-y wisdom

**Comment by pnrobinson** [comment]
I would say our goals are
1. Any body can use the software
2. Nobody sues us
I thought that was what GNU does -- and it also encourages other people to play the same game?

What advantage do the other licenses have actually?

**Comment by kltm** [comment]
I tend to prefer and recommend BSD-3 clause for software (over MIT). If somebody realistically thinks patents are an issue, there is Apache.
GPL is...complicated and can prevent reuse is others do not use the same license. If one is joining a body of software that already uses it, it's fine. For new works, something more permissive generally plays better with the community.

**Comment by pnrobinson** [comment]
@kltm Thankls!
So is everybody ok with BSD3 ?

**Comment by justaddcoffee** [comment]
> So is everybody ok with BSD3 ?

+1 BSD3

**Comment by pnrobinson** [comment]
https://github.com/monarch-initiative/N2V/pull/152

Please acccept if OK. You need to say (c) by -- I put Monarch Initiative if that is OK?
