### ISSUE TITLE
Need file for testing read_databz2 of class TextEncoder

### ISSUE THREAD

**Issue by LucaCappelletti94** [monarch-initiative/N2V#23]
I need a bz2 file to test the [`read_databz2`](https://github.com/TheJacksonLaboratory/N2V/blob/38664057ac05b336bd5da7db01bee73f7cb54b73/n2v/text_encoder.py#L65) method of the class [`TextEncoder `](https://github.com/TheJacksonLaboratory/N2V/blob/38664057ac05b336bd5da7db01bee73f7cb54b73/n2v/text_encoder.py#L11).

Thank you!

**Comment by pnrobinson** [comment]
Hi Luca!
we were using a pretty large file in bz2 format that was about 5 Gb of wikipedia. I am not sure we really need this method for the package but it might be convenient to keep. If you want to test the method, I would suggest creating a small file with 5 sentences and then just creating a bz2 file for the test archive. Something like this:

sudo apt install bzip2
bzip2 -z filename

**Comment by LucaCappelletti94** [comment]
From which file I could extract a few sentences that could be useful in this test?

**Comment by pnrobinson** [comment]
I think there is not too much to test here. Basically the only thing to test is if we extract sentences from a bzip'd file.

**Comment by LucaCappelletti94** [comment]
Ok, still from which one of the files I could extract the sentences?

Thanks!

**Comment by pnrobinson** [comment]
I think we can close this - this functionality should not be in the core library
