### ISSUE TITLE
Class ContinuousBagOfWordsWord2Vec is never used

### ISSUE THREAD

**Issue by LucaCappelletti94** [monarch-initiative/N2V#25]
Since the class [`ContinuousBagOfWordsWord2Vec`](https://github.com/TheJacksonLaboratory/N2V/blob/306d14690ff2834604dbba0b27c7ded5a8521450/n2v/word2vec.py#L335) is never used I was wondering if it will ever be, and if that was to be the case we should remove it.

If it is useful, which parameters could I use for adding a simple test for the class?

**Comment by pnrobinson** [comment]
@LucaCappelletti94  The CBOW does not work yet. I am also thinking that we should refactor the word2vec code to use the inheritance based keras framework. Therefore it might be good to wait a little bit before adding tests. I would suggest the architecture be
Word2Vec (superclass)
-- deals with parameters and has common set of methods for things like getters (accuracy history etc)

SkipGram
CBOW
Possibly Glove

-- the constructors of these classes use keras classes for Loss, Optimizer etc that actually implement the word2vec family algorithms. One keras "model" is constructed in the constructor of each subclass
-- the get_next_batch is different from SG and CBOW and so this is in the subclass
-- mwe

**Comment by vidarmehr** [comment]
CBOW has been implemented. So, I close this issue.
