### ISSUE TITLE
Graph class too dependent on node names

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#26]
right now the graph class expects the class of nodes to be encoded with the first character of the name. We should consider keep that for now, but if any of the nodes does not start with a letter, disactivating the heterogeneous algorithm.

**Comment by vidarmehr** [comment]
I fixed the issue with my code. It was actually not related to CFSGraph class. Also, it does not seem to me that nodes must start with a letter:

`fields = line.rstrip('\n').split()`
`if not len(fields) == 3:`
          `print("[ERROR] Skipping malformed line with {} fields ({}).".format(len(fields), line))`
           `continue`
`nodeA = fields[0]`
`nodeB = fields[1]`

**Comment by vidarmehr** [comment]
@pnrobinson I think we can close this issue. CSFGraph class does not depend on the first character of the name.

**Comment by justaddcoffee** [comment]
Could we revisit this at some point, maybe on the next Thursday meeting? I think I'm close to getting the heterogeneous graph fxn working, but we maybe could improve how the code deals with node types. 

One possibility would be to make a node class, and capture node type as an attribute of this class
