### ISSUE TITLE
Move to Monarch GitHub

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#34]
We cannot use CI on the JAX github and thus we will need to move this repo. I will do so later on today -- please shout if there are any issues

**Comment by LucaCappelletti94** [comment]
Looking forward to integrating the CIs :)

**Comment by pnrobinson** [comment]
@LucaCappelletti94  done -- we should be able to add the CIs. Let me know when you have time!

**Comment by LucaCappelletti94** [comment]
Would 10 AM EST be ok for you? Since I am not in the Monarch organization on GitHub I cannot add the CIs myself, but I could guide you do so via a Skype call.

Otherwise, you could add me to the Monarch GitHub organization and I can add them myself.

**Comment by pnrobinson** [comment]
10AM is ok -- I will be on skype
