### ISSUE TITLE
[item for sublist in sentences for item in sublist] not working

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#39]
flat_list_of_words = [item for sublist in sentences for item in sublist]

this seems to be turning texts into plain letters and unittests are failing

**Comment by callahantiff** [comment]
I will check it out now. I tested it last week and it seemed OK.

**Comment by pnrobinson** [comment]
I think the issue is that we are using this
encoder.build_dataset_in_sentences()
which is turning the words into chars
probably we should be using
encoder.build_dataset()
but still tests are not being passed...

**Comment by callahantiff** [comment]
Sounds good, there are other scripts (e.g. `runAnalysis.py`) that also has bugs i am working on fixing. Caught them when trying to test the code in the PR. Sorry for not approving earlier. I will work on trying to get it all running on my end this morning.

**Comment by pnrobinson** [comment]
ps, I just merged cbow.

**Comment by callahantiff** [comment]
Thanks! Found the bug in `text_encoder.py` and fixed it. Should be working now. I am going to go back to checking `RunAnalysis` now. let me know if you have any problems with `text_encoder.py`.

**Comment by callahantiff** [comment]
All tests on `text_encoder.py` are passing now. I think this can be closed now.

**Comment by pnrobinson** [comment]
thanks, yes everything is passing & the CI is now running!
