### ISSUE TITLE
TestSkipGramWord2Vec

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#42]
This currently does not actually test anything. It is hard to test the actual production of embeddded vectors, but we should move the production of the vectors to a setup method and then test a few things such as the number of walks etc.

**Comment by callahantiff** [comment]
I noticed that only the CBOW implementation is tested in the `test_word2vec.py` file. Should we add a test for the skipgram model to this file?

I also think we might want to extend some of the current tests to include explicit evaluations of functionality of methods. Might be easiest to wait until after refactoring to do this.

**Comment by pnrobinson** [comment]
I was thinking of having one class for each of the batchers and making a separate test file for each of them. We should figure out what else we want to test within the refactor word2vec class.

**Comment by pnrobinson** [comment]
I think this issue is stale and also partially implemented. Closing.
