### ISSUE TITLE
generate_hn2v_input_file "run pairdc" message

### ISSUE THREAD

**Issue by callahantiff** [monarch-initiative/N2V#43]
I'm trying to run the `generate+hn2v_input_file.py` script and trigger the following message:

>You need to run pairdc and put its output file (e.g., g2d_associations_training_6_2014.tsv) into the data directory.
>Could not find data/g2d_associations_training_4_2014.tsv

I know that I need to do something to the downloaded GTEx data file, but what is "pairdc"? From the printed message, I am unclear on how to how to complete the task. If this script is included in the package, I think this message might also be a source of confusion for end users. Perhaps we can add some additional detail to the message?

**Comment by pnrobinson** [comment]
I think that we need to remove this script from the repository -- it will go into the evaluation repository instead if at all. We should only have small self-contained tests in the xn2v package. I can remove the file it is is easier.

**Comment by callahantiff** [comment]
Can we leave it for now?I just wanted to build structures needed to test the scripts in the `xn2v` package. I suppose that I can pull the data files from the `tests/data` repo instead.

I also noticed that the `runW2V.py` file got deleted, but I kept a local version since it's been very useful for debugging.

**Comment by pnrobinson** [comment]
Let's just leave it. I think the functionality of runW2V.py is now in runAnalysis.py

**Comment by justaddcoffee** [comment]
> I also noticed that the runW2V.py file got deleted, but I kept a local version since it's been very useful for debugging.

Sorry, that was me - it's not gone per se, just moved into `runAnalysis.py` to keep things tidy. You can run `runW2V` by running this command:
`python runAnalysis.py run-w2v-test`

**Comment by pnrobinson** [comment]
btw Justin -- it looks like click is using the function names for the commands. Is ther some way of providing a short alias name (e.g. w2v instead of run-w2v-test) ?

**Comment by justaddcoffee** [comment]
Sure, [here's a PR](https://github.com/monarch-initiative/N2V/pull/44) - feel free to change more command/function names

**Comment by pnrobinson** [comment]
I think this issue has gotten stale, closing. Reopen if necessary!
