### ISSUE TITLE
remove/move test file

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#49]
tests/test_n2v.py

- this file is causing a travis error with the coverage because url.request is not working. The file is testing import functions that we want to move out of this project anyway. I would suggest we move the test elsewhere @vidarmehr

**Comment by vidarmehr** [comment]
We have this test in IDG2KG repository tests/test_hn2v. Maybe we can still keep that in IDG2KG and remove tests/test_n2v from this repository (N2V).

**Comment by vidarmehr** [comment]
test/test_n2v.py and tests/n2vParser.py were removed.
