### ISSUE TITLE
SkipGram fails on embedding a protein-protein interaction file

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/N2V#54]
I created a new branch called link_prediction_ppi in which I am testing graph embedding and link prediction on protein-protein interaction graph. In the first step, I just tried to embed the training graph with SkipGram. The algorithm fails, while it successfully run on karate.train graph.
The error is:
>Traceback (most recent call last):
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 52, in <module>
    model.train(display_step=2)
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/word2vec.py", line 414, in train
    batch_x, batch_y = self.next_batch_from_list_of_lists(walkcount, self.num_skips, self.skip_window)
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/word2vec.py", line 377, in next_batch_from_list_of_lists
    current_batch, current_labels = self.next_batch(sentence, batch_count, num_skips, skip_window)
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/word2vec.py", line 341, in next_batch
    batch[i * num_skips + j] = buffer[skip_window]
ValueError: invalid literal for int() with base 10: 'ENSP00000264028'

Does anyone know what cases this issue? In karate.train, nodes are integers, but in ppi graph, nodes are ensembl ids likeENSP00000264028. Do you think it might have caused the error?
Thank you.

**Comment by callahantiff** [comment]
The error message that you listed does seem to suggest that the problem is that an integer is expected, but it's getting passed a string. Can you try it with the same graph, but first map the string labels to integers?

**Comment by vidarmehr** [comment]
Thank you, Tiffany. Ok. I will map string labels to integers. But, I thought the type of data does not matter for SkipGram.

**Comment by callahantiff** [comment]
@vidarmehr - Great question! So, the current version of SkipGram does expect the data to be input as integers.

That said, I think `text_encoder.py()` is currently intended to be used for free-text input, but I don't see why it could not be extended to also handle paths with labels. Perhaps that is something worth talking about further on Thursday during our paired session.

**Comment by vidarmehr** [comment]
@callahantiff Thank you very much for your explanations, Tiffany! Yes. We should extend SkipGram to encode text data, too.

 I mapped the string data to int. But, now I get another error.

> Traceback (most recent call last):
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 54, in <module>
    model.train(display_step=10000)
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/word2vec.py", line 417, in train
    self.run_optimization(batch_x, batch_y)
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/word2vec.py", line 391, in run_optimization
    emb = self.get_embedding(x)
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/word2vec.py", line 273, in get_embedding
    x_embed = tf.nn.embedding_lookup(self.embedding, x)
  File "/Users/ravanv/anaconda3/envs/N2V/lib/python3.7/site-packages/tensorflow_core/python/ops/embedding_ops.py", line 364, in embedding_lookup_v2
    return embedding_lookup(params, ids, "div", name, max_norm=max_norm)
  File "/Users/ravanv/anaconda3/envs/N2V/lib/python3.7/site-packages/tensorflow_core/python/ops/embedding_ops.py", line 317, in embedding_lookup
    transform_fn=None)
  File "/Users/ravanv/anaconda3/envs/N2V/lib/python3.7/site-packages/tensorflow_core/python/ops/embedding_ops.py", line 135, in _embedding_lookup_and_transform
    array_ops.gather(params[0], ids, name=name), ids, max_norm)
  File "/Users/ravanv/anaconda3/envs/N2V/lib/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/Users/ravanv/anaconda3/envs/N2V/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 3965, in gather
    return params.sparse_read(indices, name=name)
  File "/Users/ravanv/anaconda3/envs/N2V/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 640, in sparse_read
    self._handle, indices, dtype=self._dtype, name=name)
  File "/Users/ravanv/anaconda3/envs/N2V/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_resource_variable_ops.py", line 670, in resource_gather
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = 3621 is not in [0, 21) [Op:ResourceGather] name: embedding_lookup/

Do you know what causes this error? Thank you.

**Comment by callahantiff** [comment]
No problem! Happy to take a look. How big is the data file? Can you upload it to this issue so I can play with it? Can you also include here the lines of code you are running when you get this error?

I have seen this error before, but I want to make sure that I can reproduce it! 😄

**Comment by vidarmehr** [comment]
@callahantiff Thanks a lot, Tiffany! Please go to the branch "link_prediction_ppi". The code is runLinkPrediction_ppi.py and the file is "pos_train_edges" which has been uploaded.

At this time, I just try to embed the  nodes in "pos_train_edges" file using SkipGram model.

**Comment by callahantiff** [comment]
@vidarmehr - Perfect, thanks for the details! I will be able to take a close look this evening and will send some updates then.

**Comment by vidarmehr** [comment]
@callahantiff I solved the issue, Tiffany! Sorry. I had made a mistake in the first parameter of SkipGram. I am going to check in the code and close this issue. Thanks again for your helps.

**Comment by callahantiff** [comment]
Nice catch @vidarmehr! I'm so glad you got everything working!

**Comment by pnrobinson** [comment]
PS. let's add some more Q/C code to the constructors. Users should get an error message like" Parameter 1 needs to be apples but you passed oranges" and not a stack trace. 
I would recommend we have code like this
```
if not isinstance(param1, apple):
   raise TypeError(" Parameter 1 needs to be apples but you passed oranges")
```

we should do this for all of the parameters!

**Comment by iimpulse** [comment]
Are these parameters for the CLI? If so please check out https://click.palletsprojects.com/en/7.x/

Click will do this for you. No need to manually write it all.

**Comment by justaddcoffee** [comment]
Second that, click is pretty handy

**Comment by vidarmehr** [comment]
> PS. let's add some more Q/C code to the constructors. Users should get an error message like" Parameter 1 needs to be apples but you passed oranges" and not a stack trace.
> I would recommend we have code like this
> 
> ```
> if not isinstance(param1, apple):
>    raise TypeError(" Parameter 1 needs to be apples but you passed oranges")
> ```
> 
> we should do this for all of the parameters!

I added Q/C code to the constructors to check the first parameter of the SkipGram. Please check the word2vec.py in link_prediction_ppi branch.

**Comment by vidarmehr** [comment]
> Are these parameters for the CLI? If so please check out https://click.palletsprojects.com/en/7.x/
> 
> Click will do this for you. No need to manually write it all.

Thanks, Mike! The parameters are not for the CLI. At this time, I just followed what Peter suggested.

**Comment by iimpulse** [comment]
Might be worth linking them up anyways and having defaults. But whatever works!

**Comment by vidarmehr** [comment]
> Might be worth linking them up anyways and having defaults. But whatever works!

Ok. Thanks, Mike!

**Comment by vidarmehr** [comment]
@pnrobinson Could you please let me know if we can close this issue? Thank you.

**Comment by pnrobinson** [comment]
I think we can close. We will need click etc primarily for the driver scripts but not for the library itself.
