### ISSUE TITLE
CSFGraph is returning the string representations of nodes but we want ints

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#56]
Write a function similar to 
```
def neighbors(self, source):
```

but it should return ints
Call it
```
def neighbors_as_ints(self, source):
```

After this is tested it should become the main method and the original method should be get_neighbors_as_string

**Comment by vidarmehr** [comment]
In the branch "get_neighbors_as_ints_csf_graph", the method neighbors_as_ints(self, source) has been written (in csf_graph.py) and tested in test_csf_graph.

**Comment by vidarmehr** [comment]
We have implemented this. Now, CFS returns indices of nodes. So, I close this issue.

**Comment by callahantiff** [comment]
> We have implemented this. Now, CFS returns indices of nodes. So, I close this issue.

I also update the tests to reflect this change 😄

**Comment by vidarmehr** [comment]
@callahantiff Thank you very much, Tiffany!
