### ISSUE TITLE
pickle the state of the CSFGraph following creation of the alias probabilities

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#57]
Make code that pickles the current state and also re-imports it. Should be unit tested. This could be a method of the CSFGraph class.

https://www.journaldev.com/15638/python-pickle-example

**Comment by vidarmehr** [comment]
I will work on it over the weekend.

**Comment by justaddcoffee** [comment]
@deepakunni3 note this ticket, similar in a way to #139, which you are working on, in case you can kill two birds with one stone
