### ISSUE TITLE
AttributeError, link prediction failed on Sumner

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/N2V#69]
The code ran for 1 day and 3 hours, but failed due to the error:

Traceback (most recent call last):
  File "/projects/robinson-lab/vidar/Node2vec_1/N2V/runLinkPrediction_ppi.py", line 53, in <module>
    model.train(display_step=2)
  File "/projects/robinson-lab/vidar/Node2vec_1/N2V/xn2v/word2vec.py", line 421, in train
    self.run_optimization(batch_x, batch_y)
  File "/projects/robinson-lab/vidar/Node2vec_1/N2V/xn2v/word2vec.py", line 399, in run_optimization
    gradients = g.gradient(loss, [self.embedding, self.nce_weights, self.nce_biases])
  File "/home/ravanv/.local/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 980, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/home/ravanv/.local/lib/python3.6/site-packages/tensorflow/python/eager/imperative_grad.py", line 76, in imperative_grad
    compat.as_str(unconnected_gradients.value))
AttributeError: 'RefVariable' object has no attribute '_id'

**Comment by pnrobinson** [comment]
Can you reproduce this error locally with a small example?

**Comment by vidarmehr** [comment]
I don't get any error message when I run the code on my machine. I tried a small example on sumner and it failed because of the same error. Stackoverflow suggests enabling eager execution mode by writing
tf.enable_eager_execution()
after import statements. I am working on it right now.

**Comment by vidarmehr** [comment]
tf.enable_eager_execution() solved the issue on Sumner.

**Comment by vidarmehr** [comment]
Enabling eager_exection() works on Sumner, but it does not work on my machine. I get the error:
"AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'"

**Comment by pnrobinson** [comment]
AFAIK eager execution is the default with tensor flow2.
Therefore, can we check what tensofrflow version was used?
We should probably have statements such as
```
assert tensor flow.__version__ >= "2.0"
```
We want to make sure we are always using tensorflow 2 for consistency

**Comment by vidarmehr** [comment]
Yes, Peter! eager execution is the default with tensorflow 2.

**Comment by vidarmehr** [comment]
I installed tensorflow 2 on Sumner and now the code was successfully completed without error or using tf.enable_eager_execution().
