### ISSUE TITLE
Codacy issue on assert tf.__version__ >= "2.0"

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/N2V#73]
I created a branch called "check_tensorflow_version". I have added 
`assert tf.__version__ >= "2.0"` to word2vec.py to check the version of tensorflow. When I create a pull request, codacy gives an issue:

> Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
> 
> B101: Test for use of assert
> This plugin test checks for the use of the Python assert{.docutils .literal .notranslate} keyword. It was discovered that some projects used assert to enforce interface constraints. However, assert is removed with compiling to optimised byte code (python -o producing *.pyo files). This caused various protections to be removed. The use of assert is also considered as general bad practice in OpenStack codebases.
> 
> Please see https://docs.python.org/2/reference/simple_stmts.html#the-assert-statement for more info on assert{.docutils .literal .notranslate}

Does anyone know what the correct way of checking the version of tensorflow is? Can we just write 'tensorflow>=2.0' in setup.py in install_requires?
Thank you.

**Comment by pnrobinson** [comment]
@vidarmehr  I think we can ignore this particular warning for now. The installation script should actually be checking for the tensor flow version and should fail unless tensorflow2 is installed. I am surprised that things worked on sumner with tensor flow 1. So I think we need to correct the installation script (setup.py). Maybe @deepakunni3 or @LucaCappelletti94  can comment here?

**Comment by justaddcoffee** [comment]
Could you just do something like this instead?

```
if tf.__version__ < 2.0:
    sys.exit("tensorflow version is {}, should be 2.0 or above", tf.__version__)
```

**Comment by LucaCappelletti94** [comment]
I believe the best approach would be by specifying the version within the setup.py.

**Comment by deepakunni3** [comment]
Yes, I would recommend just making sure that the proper version is specified in setup.py
Having version checks in different scripts might be tedious in the long run.

**Comment by deepakunni3** [comment]
Also, the reason codacy is throwing a warning about `assert` is because `assert` shouldn't be used in actual code. Its more for debugging and primarily used in testing.

**Comment by vidarmehr** [comment]
Thank you very much everyone!
@pnrobinson So, I think the best approach is to specify the version of tensorflow in the setup.py.

**Comment by LucaCappelletti94** [comment]
I have already applied the change in a pull request

**Comment by vidarmehr** [comment]
> I have already applied the change in a pull request

Oh, Ok!  Thank you Luca!
