### ISSUE TITLE
test_raw_probs

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#78]
CHeck this unit test -- we commented it out.,

**Comment by vidarmehr** [comment]
original_probs returns negative values. Working on this issue.

**Comment by vidarmehr** [comment]
@pnrobinson I am working on this issue in branch update_hetrogenous_graph_code. I know what caused the error. I made some changes, but the hetnode2vec.py still needs some modficiations. Working on the tests to make sure all tests pass.

**Comment by vidarmehr** [comment]
I have modified _preprocess_transition_probs_xn2v and  get_alias_edge_xn2v. I have added some more tests. Now, all tests are passed. 
Justin had modified the code so that node indices were used. However, I had changed it to the old format. I need to change it back to what Justin had implemented.

**Comment by vidarmehr** [comment]
Tests are passed. I think we can close this issue.
