### ISSUE TITLE
key error when running runLinkPrediction_ppi.py

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/N2V#83]
running `runLinkPrediction_ppi.py` on edges generated from the first 10k lines of the String DB, I'm getting a key error here:

https://github.com/monarch-initiative/N2V/blob/e159e15bedc89dacc5e8e30a2e53f8bfc8586daf/xn2v/hetnode2vec.py#L62

```
Walk iteration:
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1415, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/jtr4v/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 144, in <module>
    main(args)
  File "/Users/jtr4v/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 137, in main
    walks = pos_train_g.simulate_walks(args.num_walks, args.walk_length)
  File "/Users/jtr4v/PycharmProjects/N2V/xn2v/hetnode2vec.py", line 85, in simulate_walks
    walks.append(self.node2vec_walk(walk_length=walk_length, start_node=node))
  File "/Users/jtr4v/PycharmProjects/N2V/xn2v/hetnode2vec.py", line 63, in node2vec_walk
    walk.append(cur_nbrs[self.alias_draw(alias_nodes[cur][0], alias_nodes[cur][1])])
KeyError: 4285
```

Seems like a bug - `cur` is an integer, but `alias_nodes` is a `dict` with gene IDs as keys, so I don't understand how `alias_nodes[cur]` on line 63 will ever work. (Possibly I'm running the code incorrectly though...)

**Comment by justaddcoffee** [comment]
I think line 63 should possibly be using `g.index_to_node_map` to look up items in `alias_nodes`, i.e. something like:

`walk.append(cur_nbrs[self.alias_draw(alias_nodes[g.index_to_node_map[cur]][0], alias_nodes[g.index_to_node_map[cur]][1])])
`

**Comment by vidarmehr** [comment]
Hi Justin,
Which branch are your using to run simulations?

**Comment by justaddcoffee** [comment]
Hi @vidarmehr - good point

Originally I was on `creating_keras_develop_branch`, but seems to happen on `develop` (commit feba457bf9858968ec19f13171ac7973cdab5812) too

**Comment by justaddcoffee** [comment]
oh, sorry, you mean which branch am I using to make the edges? `creating_keras_develop_branch`

Maybe that's the problem

**Comment by callahantiff** [comment]
> oh, sorry, you mean which branch am I using to make the edges? `creating_keras_develop_branch`
> 
> Maybe that's the problem

If it's any help, I noticed that there were changes made on `develop` last week to output node identifiers as integers. As a result, I updated one of the test files on the `creating_keras_develop_branch` branch to reflect this change. I have not yet made any changes to the file mentioned in your error on this branch, so I am guessing like the test file it will also need an update.  If that is the case, it should be an easy fix. I can try and make it now, if that would help?

**Comment by vidarmehr** [comment]
Justin, could you please use the branch "link_prediction_with_CBOW_skipgram_and_3_classifiers"?
The input files are in tests/data/ppismall.
If your input files are in the format of the files in tests/data/ppismall, then you should be fine. Please let me know if you still have any issues.

I made a pull request from the branch that I mentioned above to develop last night and asked Peter to review the changes that I made. Unfortunately, he has been sick since this morning and I am not sure if he cad a chance to look at it.

Thanks!

**Comment by callahantiff** [comment]
I found what's causing the error on the `creating_keras_develop_branch`. If it's helpful, I can commit the changes so that you can test on this branch until Peter approves Vida's changes? Otherwise, ignore me 😄

**Comment by pnrobinson** [comment]
I have been a bit sick recently, but if there are no controversies, just go ahead and merge!

**Comment by justaddcoffee** [comment]
thanks @vidarmehr (and @callahantiff!)  - `runLinkPrediction_ppi.py` works on `link_prediction_with_CBOW_skipgram_and_3_classifiers` branch, thanks! 

Just trying to walk through all the code and make sure I understand, this helps a lot! Talk to you guys at 11
