### ISSUE TITLE
click vs. argparse?

### ISSUE THREAD

**Issue by callahantiff** [monarch-initiative/N2V#84]
@vidarmehr and @pnrobinson - Just wanted to check-in and see if there was decision made about using `argparse` or `click`?

Happy to help make the conversion once a decision is made.

**Comment by justaddcoffee** [comment]
This possibly is my fault - I introduced the `click` dependency, but I think `argparse` is fine too. @vidarmehr which do you prefer?

**Comment by deepakunni3** [comment]
Click allows for a command line entrypoint into your code. This allows for easy tagging of methods that are to be exposed via command line and a set of arguments to go with it.

I was under the impression that argparse was only for defining arguments to single python script where the execution is usually via `__main__`.

**Comment by pnrobinson** [comment]
Please note that for the final library we will probably remove the command line scripts and we might not want to add click annotations to the other classes?

**Comment by vidarmehr** [comment]
I would prefer argparse. But, I am fine with changing it to click. However,  I think at this time we can keep argparse and for the final version we decide which one to use.

**Comment by vidarmehr** [comment]
@pnrobinson  I have used argparse to run link predictions. Can we close this issue?

**Comment by pnrobinson** [comment]
I am closing, it looks like we are done--reopen if needed.
