### ISSUE TITLE
Adding type checking to tests

### ISSUE THREAD

**Issue by callahantiff** [monarch-initiative/N2V#86]
Wanted to get your thoughts on using [`Mypy`](http://mypy-lang.org/) or [`pytyp`](https://github.com/google/pytype/blob/master/docs/user_guide.md) ? `pytyp` is from Google and while mentioned in the [Style Guide](http://google.github.io/styleguide/pyguide.html), is not explicitly stated as the only type checker that can eb used.

**mypy:** Once we have added type hints to all scripts, we could extend the existing tests to include type checking. The documentation seems pretty straight forward (example from [RealPython](https://realpython.com/python-type-checking/)):

```python
# headlines.py

def headline(text: str, align: bool = True) -> str:
    if align:
        return f"{text.title()}\n{'-' * len(text)}"
    else:
        return f" {text.title()} ".center(50, "o")

print(headline("python type checking"))
print(headline("use mypy", align="center"))
```

```shell
$ mypy headlines.py
headlines.py:10: error: Argument "align" to "headline" has incompatible
                        type "str"; expected "bool"
```

**Comment by justaddcoffee** [comment]
@callahantiff either is fine with me - possibly `pytyp` might be better if we are going on in with the Google styleguide

**Comment by deepakunni3** [comment]
@callahantiff I used mypy before, but switched to the default [typing](https://docs.python.org/3/library/typing.html) module in Python 3.5+

If enforcing typing at run time is critical then pytyp seems to do a better job and it does build off of Typing module.

**Comment by callahantiff** [comment]
Perfect. The `typing` module seems best. If some reason we want to use `mytyp` or `ptyp` the scripts would not need editing. 

I am going to update the scripts I have been editing them to better leverage the `typing` module. Should be a quick fix.

**Comment by callahantiff** [comment]
Quick update -- I am working on adding in typing as I work on the refactor. I looked into `mypy` a bit more and think that it might be the better option. It was created by Guido Van Rossum and has WAY better documentation than `pytyp`. I'm happy to switch if there are strong arguments against this, but for now I am moving forward with it.

**Helpful Documentation:** [cheat sheet](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)  

**Running Type Checking:**
```bash
# checking a full directory of scripts
mypy mypy --strict-optional xn2v

# checking a single script
mypy mypy --strict-optional xn2v/w2v/cbow_list_batcher
```

**Notes + Caveats:**  _I will update this issue as they come up and will leave `# TODO` comments within the scripts_ 
- Not all libraries are covered and while we can use stubbing, I'm not going to do that at this time. You can tell which libraries are ignored within a script by looking for `# type: ignore` in the module import section (e.g. `import numpy as np   # type: ignore`)
- There do seem to be some bugs around typing of dictionaries, which can be `None` (details [here](https://github.com/python/mypy/issues/4359)).

**Comment by justaddcoffee** [comment]
@callahantiff can we close this ticket?

I like `mypy` and enforcing typehints generally btw, thanks for incorporating this

**Comment by callahantiff** [comment]
> @callahantiff can we close this ticket?
> 
> I like `mypy` and enforcing typehints generally btw, thanks for incorporating this

@justaddcoffee - absolutely, good to go on this! I will close it now. Thanks @justaddcoffee!
