### ISSUE TITLE
error in test_version.py

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/N2V#89]
Does anyone  know what tests/test_version.py tests? Do we need it? I get an error when I run it.

> ERROR: Failure: ModuleNotFoundError (No module named 'validate_version_code')

Thank you.

**Comment by justaddcoffee** [comment]
Hi @vidarmehr - I can't reproduce this - how are you running the test?

**Comment by vidarmehr** [comment]
@justaddcoffee  Hi Justin, Thank you for your quick reply. 
Apparently, there is an error (the unresolved reference) in: `from validate_version_code import validate_version_code`.  But, I don't know how solve it.
I am using pycharm and to run the test, I just simply click on "run" (small green triangle) next to def test_version(self).

**Comment by pnrobinson** [comment]
Were you able to install the package?

**Comment by justaddcoffee** [comment]
@vidarmehr when I run this in the same way, I see this output - possibly could compare this with how Pycharm is running the test on your end:

```
Testing started at 1:15 PM ...
/Users/jtr4v/PycharmProjects/N2V/venv/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_nosetest_runner.py --target test_version.py::TestTextEncoderSentences.test_version
Launching Nosetest with arguments /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_nosetest_runner.py test_version.py:TestTextEncoderSentences.test_version in /Users/jtr4v/PycharmProjects/N2V/tests

.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK

Process finished with exit code 0
```

**Comment by vidarmehr** [comment]
Oh, sorry. I solved the issue. Thank you @justaddcoffee and @pnrobinson.
I was not able to install the package with pycharm. But, I pip install validate_version_code and it worked. So ,I close the issue.
